Multiteca/Multiteca/Multiteca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Multiteca.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Multiteca/Multiteca/Multiteca/Controllers/Juegos/ColeccionController.cs
using Multiteca.Models.Juego;
using Multiteca.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Multiteca.Controllers.Juego
{
    public class ColeccionController : Controller
    {
        private IJuegoService JuegoService = new JuegoService();

        // GET: ListaJuego
        public ActionResult Index()
        {
            List<ColeccionModel> colecciones = JuegoService.ColeccionList();
            return View(colecciones);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Saga = new SelectList(JuegoService.SagaList(), "Id", "Nombre", null);
            return View("Create", new ColeccionModel());
        }

        [HttpPost]
        public ActionResult Create(ColeccionModel coleccion)
        {
            JuegoService.CrearColeccion(coleccion);
            ViewBag.Saga = new SelectList(JuegoService.SagaList(), "Id", "Nombre", coleccion.Saga != null ? coleccion.Saga.Id.ToString() : null);
            return View("Edit", coleccion);
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var coleccion = JuegoService.GetColeccionById(id);
            ViewBag.Saga = new SelectList(JuegoService.SagaList(), "Id", "Nombre", coleccion.Saga != null ? coleccion.Saga.Id.ToString() : null);
            return View("Edit", coleccion);
        }

        [HttpPost]
        public ActionResult Edit(ColeccionModel coleccion)
        {
            JuegoService.ModificarColeccion(coleccion);

            List<ColeccionModel> colecciones = JuegoService.ColeccionList();
            return View("Index", colecciones);
        }

        // GET: Default/Delete/5
        public ActionResult Delete(Guid id)
        {
            var coleccion = JuegoService.GetColeccionById(id);
            ViewBag.Saga = new SelectList(JuegoService.SagaList(), "Id", "Nombre", coleccion.Saga != null ? coleccion.Saga.Id.ToString() : null);
            return View("Delete", coleccion);
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, ColeccionModel coleccion)
        {
            try
            {
                JuegoService.EliminarColeccion(coleccion);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Multiteca/Multiteca/Multiteca/Controllers/Juegos/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Multiteca.Controllers.Juegos
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        // GET: Default/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Multiteca/Multiteca/Multiteca/Controllers/Juegos/JuegoController.cs
using Multiteca.Models.Juego;
using Multiteca.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Multiteca.Controllers.Juego
{
    public class JuegoController : Controller
    {
        private IJuegoService JuegoService = new JuegoService();

        // GET: ListaJuego
        public ActionResult Index()
        {
            List<ListaJuegoModel> juegos = JuegoService.GetList();
            return View(juegos);
        }

        // GET: ListaJuego/Edit/5
        public ActionResult Edit(Guid id)
        {
            JuegoModel juego = JuegoService.GetById(id);

            ViewBag.Saga = new SelectList(JuegoService.SagaList(), "Id", "Nombre", juego.Saga != null ? juego.Saga.Id.ToString() : juego.Coleccion != null ? juego.Coleccion.Saga.Id.ToString() : null);
            ViewBag.Coleccion = new SelectList(JuegoService.ColeccionList(), "Id", "Nombre", juego.Coleccion != null ? juego.Coleccion.Id.ToString() : null);
            ViewBag.Desarrollador = new SelectList(JuegoService.DesarrolladorList(), "Id", "Nombre", juego.Desarrollador != null ? juego.Desarrollador.Id.ToString() : null);
            ViewBag.Distribuidor = new SelectList(JuegoService.DistribuidorList(), "Id", "Nombre", juego.Distribuidor != null ? juego.Distribuidor.Id.ToString() : null);
            ViewBag.PlataformaDeseada = new SelectList(JuegoService.PlataformaList(), "Id", "Nombre", juego.PlataformaDeseada != null ? juego.PlataformaDeseada.Id.ToString() : null);
            ViewBag.Tienda = new SelectList(JuegoService.TiendaList(), "Id", "Nombre", juego.TiendaComprado != null ? juego.TiendaComprado.Id.ToString() : null);
            ViewBag.PlataformaCompra = new SelectList(JuegoService.PlataformaList(), "Id", "Nombre", juego.PlataformaCompra != null ? juego.PlataformaCompra.Id.ToString() : null);
            ViewBag.FormatoCompra = new SelectList(JuegoService.FormatoList(), "Id", "Nombre", juego.FormatoCompra != null ? juego.FormatoCompra.Id.ToString() : null);

            return View("Edit", juego);
        }

        // GET: ListaJuego/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ListaJuego/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ListaJuego/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Multiteca/Multiteca/Multiteca/Views/Coleccion/Create.cshtml
@model Multiteca.Models.Juego.ColeccionModel

<div class="row">
    <h2>Nueva colección</h2>
</div>

@using (Html.BeginForm("Create", "Coleccion", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div class="row">
        <div class="form-group col-md-8">
            @Html.LabelFor(model => model.Nombre):
            @Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control" })
        </div>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Saga):
            @Html.DropDownListFor(model => model.SagaId, (IEnumerable<SelectListItem>)ViewBag.Saga, "- Seleccione -", new { @class = "form-control" })
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Descripcion)
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @rows = "3" })
        </div>
    </div>

    <div class="botonera botonera-right">
        <input type="submit" class="btn btn-success" value="Crear" />
        @Html.ActionLink("Volver", "index", null, new { @class = "btn btn-primary" })
    </div>
}

Multiteca/Multiteca/Multiteca/Views/Coleccion/Delete.cshtml
@model Multiteca.Models.Juego.ColeccionModel

<div class="row">
    <h2>Nueva colección</h2>
</div>

@using (Html.BeginForm("Delete", "Coleccion", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div class="row">
        <div class="form-group col-md-8">
            @Html.LabelFor(model => model.Nombre):
            @Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Saga):
            @Html.DropDownListFor(model => model.SagaId, (IEnumerable<SelectListItem>)ViewBag.Saga, "- Seleccione -", new { @class = "form-control", @readonly = "readonly", @disabled = "true" })
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Descripcion)
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @rows = "3", @readonly = "readonly" })
        </div>
    </div>

    <div class="botonera botonera-right">
        <input type="submit" class="btn btn-danger" value="Borrar" />
        @Html.ActionLink("Volver", "index", null, new { @class = "btn btn-primary" })
    </div>
}

Multiteca/Multiteca/Multiteca/Views/Coleccion/Edit.cshtml
@model Multiteca.Models.Juego.ColeccionModel

<div class="row">
    <h2>Colección: @Model.Nombre</h2>
</div>

@using (Html.BeginForm("Edit", "Coleccion", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(x => x.Id)

    <div class="row">
        <div class="form-group col-md-8">
            @Html.LabelFor(model => model.Nombre):
            @Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control" })
        </div>
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Saga):
            @Html.DropDownListFor(model => model.SagaId, (IEnumerable<SelectListItem>)ViewBag.Saga, "- Seleccione -", new { @class = "form-control" })
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Descripcion)
            @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control", @rows = "3" })
        </div>
    </div>

    <div class="botonera botonera-right">
        <input type="submit" class="btn btn-success" value="Modificar" />
        @Html.ActionLink("Volver", "index", null, new { @class = "btn btn-primary" })
    </div>
}

Multiteca/Multiteca/Multiteca/Views/Coleccion/index.cshtml
@model IEnumerable<Multiteca.Models.Juego.ColeccionModel>
@using System.IO

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Nombre)</th>
            @*<th scope="col">@Html.DisplayNameFor(model => model.Descripcion)</th>*@
            <th scope="col">@Html.DisplayNameFor(model => model.Saga)</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="td-width-250">@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td class="td-width-100">
                    @if (item.Saga != null)
                    {
                        @Html.DisplayFor(modelItem => item.Saga.Nombre)
                    }
                    else
                    {
                        <label>-</label>
                    }
                </td>

                <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                <td class="td-width-50 td-button-case">
                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil btn btn-primary" })
                    @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>

Multiteca/Multiteca/Multiteca/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Multiteca/Multiteca/Multiteca/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Multiteca/Multiteca/Multiteca/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Multiteca/Multiteca/Multiteca/Views/Juego/Edit.cshtml
@model Multiteca.Models.Juego.JuegoModel

<div class="row">
	<h2>@Model.Nombre</h2>
</div>

<form>
	<script type="text/javascript">

		$(document).ready(function () {
			if ($('#Deseado').prop('checked') == false) {
				$('.compra-input').attr('disabled', 'disabled');
			}
			else {
				$('.compra-input').removeAttr("disabled");
			}

			if ($('#Deseado').prop('checked') == false) {
				$('.deseado-input').attr('disabled', 'disabled');
			}
			else {
				$('.deseado-input').removeAttr('disabled');
			}

			$('#Deseado').change(function () {
				if ($('#Deseado').prop('checked') == false) {
					$('.deseado-input').attr('disabled', 'disabled');
				}
				else {
					$('.deseado-input').removeAttr('disabled');
				}
			});

			$('#Comprado').change(function () {
				if ($('#Comprado').prop('checked') == false) {
					$('.compra-input').attr('disabled', 'disabled');
				}
				else {
					$('.compra-input').removeAttr("disabled");
				}
			});
		});
	</script>

	<div class="row">
		<div class="col-md-3">
			<div class="row">
				<div class="col-md-12 img-form-container">
					<img id="GameCover" src="@string.Format("/Resources/Juegos/Covers/{0}.jpg", Model.Id.ToString())" />
					<input id="GameCoverFileUpload" type="file" />
				</div>
			</div>
		</div>

		<div class="col-md-9">
			<div class="row">
				<div class="form-group col-md-8">
					@Html.LabelFor(model => model.Nombre):
					@Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control" })
				</div>
				<div class="form-group col-md-4">
					@Html.LabelFor(model => model.FechaLanzamiento):
					@Html.TextBoxFor(model => model.FechaLanzamiento, null, new { @class = "form-control" })
				</div>

				<div class="form-group col-md-5">
					@Html.LabelFor(model => model.Saga):
					@Html.DropDownListFor(model => model.SagaId, (IEnumerable<SelectListItem>)ViewBag.Saga, "- Seleccione -", new { @class = "form-control" })
				</div>
				<div class="form-group col-md-5">
					@Html.LabelFor(model => model.Coleccion)
					@Html.DropDownListFor(model => model.ColeccionId, (IEnumerable<SelectListItem>)ViewBag.Coleccion, "- Seleccione -", new { @class = "form-control" })
				</div>
				<div class="form-group col-md-2">
					@Html.LabelFor(model => model.NumColeccion)
					@Html.TextBoxFor(model => model.NumColeccion, null, new { @class = "form-control" })
				</div>

				<div class="form-group col-md-5">
					@Html.LabelFor(model => model.Desarrollador)
					@Html.DropDownListFor(model => model.DesarrolladorId, (IEnumerable<SelectListItem>)ViewBag.Desarrollador, "- Seleccione -", new { @class = "form-control" })
				</div>
				<div class="form-group col-md-5">
					@Html.LabelFor(model => model.Distribuidor)
					@Html.DropDownListFor(model => model.DistribuidorId, (IEnumerable<SelectListItem>)ViewBag.Distribuidor, "- Seleccione -", new { @class = "form-control" })
				</div>
				<div class="form-group col-md-2">
					<label for="PrecioPropuesto">Precio prop.</label>
					@Html.TextBoxFor(model => model.PrecioPropuesto, null, new { @class = "form-control" })
				</div>
			</div>
		</div>

		<fieldset class="border col-md-12">
			<legend>Deseado</legend>
			<div class="row">
				<div class="form-group col-md-12">
					<div class="input-checkbox-container">
						<i class="glyphicon glyphicon-ok"></i>
						@Html.CheckBoxFor(model => model.Deseado, new { @class = "form-group" })
					</div>
					@Html.LabelFor(model => model.Deseado)
				</div>

				<div class="form-group col-md-4">
					@Html.LabelFor(model => model.PlataformaDeseada)
					@Html.DropDownListFor(model => model.PlataformaDeseadaId, (IEnumerable<SelectListItem>)ViewBag.PlataformaDeseada, "- Seleccione -", new { @class = "form-control deseado-input" })
				</div>
			</div>
		</fieldset>

		<fieldset class="border col-md-12">
			<legend>Comprado</legend>
			<div class="row">
				<div class="form-group col-md-12">
					<div class="input-checkbox-container">
						<i class="glyphicon glyphicon-ok"></i>
						@Html.CheckBoxFor(model => model.Comprado, new { @class = "form-group input-checkbox" })
					</div>
					@Html.LabelFor(model => model.Comprado)
				</div>

				<div class="form-group col-md-4">
					@Html.LabelFor(model => model.TiendaComprado)
					@Html.DropDownListFor(model => model.TiendaCompradoId, (IEnumerable<SelectListItem>)ViewBag.Tienda, "- Seleccione -", new { @class = "form-control compra-input" })
				</div>
				<div class="form-group col-md-2">
					@Html.LabelFor(model => model.PrecioCompra)
					@Html.TextBoxFor(model => model.PrecioCompra, null, new { @class = "form-control compra-input" })
				</div>
				<div class="form-group col-md-3">
					@Html.LabelFor(model => model.PlataformaCompra)
					@Html.DropDownListFor(model => model.PlataformaCompraId, (IEnumerable<SelectListItem>)ViewBag.PlataformaCompra, "- Seleccione -", new { @class = "form-control compra-input" })
				</div>
				<div class="form-group col-md-3">
					@Html.LabelFor(model => model.FormatoCompra)
					@Html.DropDownListFor(model => model.FormatoCompraId, (IEnumerable<SelectListItem>)ViewBag.FormatoCompra, "- Seleccione -", new { @class = "form-control compra-input" })
				</div>
			</div>
		</fieldset>
	</div>
</form>

Multiteca/Multiteca/Multiteca/Views/Juego/index.cshtml
@model IEnumerable<Multiteca.Models.Juego.ListaJuegoModel>
@using System.IO

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="repeater-container">
    @foreach (var item in Model)
    {
        <div class="repeater-item">
            <span class="repeater-item-title">@Html.DisplayFor(modelItem => item.Nombre)</span>
            <div class="row">
                <div class="col-md-3">
                    <img class="repeater-item-image" alt="@item.Nombre" src="@string.Format("/Resources/Juegos/Covers/{0}.jpg", item.Id.ToString())" />
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Coleccion):</label>
                            <label>@Html.DisplayFor(modelItem => item.Coleccion)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Saga):</label>
                            <label>@Html.DisplayFor(modelItem => item.Saga)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Generos):</label>
                            <label>@Html.DisplayFor(modelItem => item.Generos)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Desarrollador):</label>
                            <label>@Html.DisplayFor(modelItem => item.Desarrollador)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Distribuidor):</label>
                            <label>@Html.DisplayFor(modelItem => item.Distribuidor)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Distribuidor):</label>
                            <label>@Html.DisplayFor(modelItem => item.Distribuidor)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Precio):</label>
                            <label>@Html.DisplayFor(modelItem => item.Precio)</label>
                        </div>
                        <div class="form-group col-md-3 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Estado):</label>
                            <label>@Html.DisplayFor(modelItem => item.Estado)</label>
                        </div>
                        <div class="form-group col-md-12 repeater-item-data">
                            <label>@Html.DisplayNameFor(model => model.Review):</label>
                            <label>@Html.DisplayFor(modelItem => item.Review)</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="repeater-item-buttoncase col-md-12">
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil btn btn-primary" })
                            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Multiteca/Multiteca/Multiteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Mi aplicación ASP.NET</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/ownScripts")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/Home">Multiteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Juegos
                    </a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						@Html.ActionLink("Juegos", "Index", "Juego", null, new { @class = "dropdown-item" })
						<div class="dropdown-divider"></div>
						@Html.ActionLink("Colección", "Index", "Coleccion", null, new { @class = "dropdown-item" })
					</div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>